### ISSUE TITLE
Ruby version > 2.0.0

### ISSUE THREAD

**Issue by deivuh** [shouya/telegram-bot#2]
Hey! 

First of all, thanks for this! Wasn't expecting something like this so soon.

I noticed that you need exactly ruby version 2.0.0, it wold be great to make it support  2.0.0 or later :)

**Comment by shouya** [comment]
you are right, thanks :)

the strict version restriction has been fixed to `> 2.0.0`.

**Comment by deivuh** [comment]
Thanks!
