### ISSUE TITLE
Undefined method `on_text'

### ISSUE THREAD

**Issue by deivuh** [shouya/telegram-bot#3]
Hi, I am getting an undefined method error.

```
`<main>': undefined method `on_text' for #<TelegramBot:0x007f8f21f85090> (NoMethodError)
```

For both `on_command` and `on_text`.

**Comment by shouya** [comment]
thanks for pointing out. it was the README that hasn't update.

you should use `on :text` and `on :command` instead.

**Comment by shouya** [comment]
readme fixed :)

**Comment by deivuh** [comment]
Thanks!
