### ISSUE TITLE
unexpected tSTRING_BEG, expecting end-of-input

### ISSUE THREAD

**Issue by deivuh** [shouya/telegram-bot#4]
I'm getting this error for the `:command` and `:text` method arguments

```
syntax error, unexpected tSTRING_BEG, expecting end-of-input
bot.on :command 'ping'  # /ping
```

**Comment by shouya** [comment]
oh, dear. thank you :) 

``` ruby
require 'telegram_bot'

bot = TelegramBot.new(token: '<your token>')
bot.listen(method: :poll, interval: 1)

p bot.get_me

bot.on :text do |txt|
  p txt
  send_chat_action :typing
  send_message txt + '😘'
  reply 'yoooooooooo'
end

bot.start!
```

Here's a valid program for you to test your bot out.

**Comment by deivuh** [comment]
Thanks again :)

**Comment by deivuh** [comment]
Sorry for reopening this, but it now gives me this error:

```
require_relative': /Library/Ruby/Gems/2.0.0/gems/telegram_bot_ruby-0.1.3/lib/telegram_bot/request.rb:10: syntax error, unexpected ',' (SyntaxError)
      def initialize(*args, token:, &block)
```

If I remove the `:`, it gives me a `NoMethodError` for the `prepend` method at the `handler.rb` file

**Comment by shouya** [comment]
sorry but i can't reproduce it. would you like to show me the part of code that caused the problem?

or perhaps you can try it on a higher version of ruby? mine is `ruby 2.2.1p85` and it works fine.

**Comment by shouya** [comment]
confirmed. named parameter requires an at least ruby 2.1 version. i will fix the requirement in gemspec on next update.

**Comment by deivuh** [comment]
You were right, I was having trouble with rbenv, so I wasn't really using ruby 2.2.2. It works great now. Thanks for your help :)
